package com.rsu.jayanthsunchu.redditsuitedup;

public class Constants {
	public static final int CONST_LOGIN_DIALOG_ID = 0;
	public static final int CONST_REFRESH_ACTIVITY_CODE = 292;
	public static final int CONST_RESULT_CODE = 291;
	public static final int CONST_RESULT_CODE2 = 293;
	public static final int CONST_SUBREDDITS_DIALOG_ID = 1;
	public static final int CONST_REFRESH_COMMENT_CODE = 420;
	public static final int CONST_RESULT_COMMENT_CODE = 421;
	
	public static final int CONST_THEME_RESULT = 992;
	public static final int CONST_THEME_REQUEST = 993;
	
	public static final String CONST_THEME_PREFS = "themeprefs";
	// Url's related to messages
	public static final String CONST_UNREAD_URL = "http://www.reddit.com/message/unread/.json?mark=true";
	public static final String CONST_MESSAGES_URL = "http://www.reddit.com/message/messages/.json?mark=true";
	public static final String CONST_COMMENTREPLY_URL = "http://www.reddit.com/message/comments/.json?mark=true";
	public static final String CONST_BYID_URL = "http://www.reddit.com/by_id/";
	public static final String CONST_SELFREPLY_URL = "http://www.reddit.com/message/selfreply/.json?mark=true";
	public static final String CONST_SENT_URL = "http://www.reddit.com/message/sent/.json";
	public static final String CONST_MODERATOR_URL = "http://www.reddit.com/message/moderator/.json?mark=true";
	public static final String CONST_ALL_URL = "http://www.reddit.com/message/inbox/.json?mark=true";

	public static final String CONST_ALLUSER_INFO = "http://www.reddit.com/user/";
	public static final String CONST_REDDITS_URL = "http://www.reddit.com/reddits/.json";
	public static final String CONST_COMMENTS_URL = "http://www.reddit.com/comments/";
	public static final String CONST_VOTE_URL = "http://www.reddit.com/api/vote";
	public static final String CONST_REPLY_URL = "http://www.reddit.com/api/comment";
	public static final String CONST_USERINFO_URL = "http://www.reddit.com/api/me.json";
	public static final String CONST_SAVE_URL = "http://www.reddit.com/api/save";
	public static final String CONST_UNSAVE_URL = "http://www.reddit.com/api/unsave";
	public static final String CONST_SUBMIT_URL = "http://www.reddit.com/api/submit";

	public static final String CONST_USERPROFILE_URL = "http://www.reddit.com/user/";
	public static final String CONST_SUBREDDITS_URL = "http://www.reddit.com/reddits/mine/.json";
	public static final String PREFS_NAME = "MyPrefsFile";
	public static final String CONST_REDDIT_URL = "http://www.reddit.com/";
	public static final String CONST_REDDIT_URL2 = "http://www.reddit.com";
	public static final String[] CONST_SUBREDDITS2 = { "User Profile",
			"Search", "Refresh", "Inbox", "Submit" };
	public static final String CONST_LOGIN_URL = "http://www.reddit.com/api/login/";
	public static final String[] CONST_SUBREDDITS = { "frontpage","0x10c", "1000words",
			"2XLookbook", "300songs", "3DS", "3dsFCswap", "412012", "4chan",
			"4sentencegamereviews", "501st", "5starmusic", "90sTrees",
			"911truth", "99percentparty", "aaaaaatheismmmmmmmmmm", "abourne",
			"academiceconomics", "AcademicPhilosophy", "Accounting",
			"AcidHouse", "AcousticOriginals", "actuallesbians", "ada",
			"Adgeek", "ads", "adventuregames", "advertising", "AdviceAnimals",
			"advocacy", "aerospace", "afghanistan", "AFOL",
			"againstmensrights", "agile", "aiclass", "aikido", "ainbow",
			"ainbowdash", "airsoft", "aiyu", "alcohol", "algorithmictrading",
			"algorithms", "Allin1", "AllOccupy", "allrages", "alltheleft",
			"AlternativeHealth", "AMA", "amateurradio", "Amazing2",
			"AmericanGovernment", "americanpirateparty", "AmericanPolitics",
			"amiga", "amishsmp", "amiugly", "anarchafeminism", "Anarchism",
			"AnarchistNews", "Anarcho_Capitalism", "ancientworldproblems",
			"Android", "androidapps", "AnimalRights", "Animals", "animation",
			"anime", "AnimeFigures", "AnimeRanks", "AnimeSketch", "annatorv",
			"Anthropology", "Anticonsumption", "anticreationism", "Antiques",
			"AntiSRSCirclejerk", "antiwar", "AnythingGoesNews",
			"AnythingGoesPics", "AnythingGoesScience", "AnythingGoesTech",
			"AnythingGoesUltimate", "apathy", "apod", "AppalachianTrail",
			"AppEngine", "apple", "applehelp", "Applejack",
			"appropriatesoftware", "aprilfools2011", "ar15", "Archaeology",
			"archiporn", "architecture", "archlinux", "arduino", "argentina",
			"arielwinter", "arizona", "arresteddevelopment", "Art", "ArtCrit",
			"ArtImages", "artshub", "asia", "asianeats", "ask", "AskACountry",
			"AskGames", "AskHistorians", "askminecraft", "AskReddit",
			"AskredditTwo", "askseddit", "asmr", "Astronomy",
			"asustransformer", "atheism", "atheismbot", "AtheistHavens",
			"AtheistMusic", "athiesm", "Atlanta", "audio", "audioinsurrection",
			"Augusta", "ausenviro", "auslaw", "Austin", "australia",
			"AustralianHeavyMusic", "austrian_economics", "autism", "Autos",
			"aviation", "awesome", "aww", "awwnime", "BabyBumps",
			"bachelor_chow", "Bacon", "badcompany2", "Bad_Cop_No_Donut",
			"baduk", "bahai", "bakchodi", "Baking", "baldursgate",
			"band_names", "bandporn", "baseball", "basement", "Basketball",
			"Bass", "bassmusic", "batmanadvice", "battlestations", "bayarea",
			"BeardPorn", "Beatmatch", "beauty", "Beekeeping", "beer",
			"beerporn", "beertrade", "Bellingham", "benswann", "bestof",
			"bestofcraigslist", "BestofF7U12", "bestofimgur", "bestoftribunal",
			"BestPodcasts", "betterthantwilight", "BF360CLAN", "BhaktiVision",
			"bicycling", "BigotryShowcase", "bigwallpapers", "bikinis",
			"bindingofisaac", "bioinformatics", "biology", "birdpics",
			"Birmingham", "bjj", "blackandwhite", "Blacksmith", "Blanketeers",
			"blender", "Blogging", "blogola", "blogs", "BMW", "boardgames",
			"bodybuilding", "bodymods", "Boise", "bollywood", "Bombing",
			"books", "BoomTimes", "Borderlands", "boringreddit", "boston",
			"BostonJobs", "Bostonmusic", "BostonSocialClub", "BotanicalPorn",
			"botany", "botcirclejerk", "Boxing", "boycotthollywood",
			"Braveryjerk", "Breadit", "breakcore", "breastfeeding",
			"BringBackToonami", "brisbane", "britishproblems", "BritishTV",
			"Brooklyn", "browsers", "BSD", "BSG", "bubbling", "Buddhism",
			"bugs", "bulgaria", "business", "CableNews",
			"cakesminerapocalypse", "CAKEWIN", "Calgary", "CalgaryPeople",
			"California", "calireggae", "CampingandHiking", "canada",
			"CanadaPolitics", "canadients", "canberra", "cancer", "cannabis",
			"Canning", "canucks", "carlhprogramming", "cars", "castit",
			"CastleStory", "Catacombs", "CatacombSnatch", "catpictures",
			"cats", "celebrities", "CelebrityFeet", "Celebs", "CemeteryPorn",
			"censorship", "CentralValley", "cesky", "cfs", "ChangeNow",
			"charactercrossovers", "charts", "ChatRoulette", "Cheap_Meals",
			"cheatatmathhomework", "checkthisout", "chemistry", "chess",
			"chicago", "ChicagoPics", "ChicagoSuburbs", "chickenfighters",
			"ChiList", "China", "ChineseLanguage", "ChloeMoretz",
			"Christianity", "chrome", "ciencia", "circlebroke", "circlejerk",
			"CIRCLEJERKMILITIA", "circlejerkpdx", "circlejerkrpg",
			"classicalguitar", "classicalmusic", "ClassicMetal",
			"ClassicScreenBeauties", "classywomen", "climate",
			"climateskeptics", "climbing", "Climbingvids", "Clojure",
			"cloud_computing", "cocktails", "codeprojects", "coding", "Coffee",
			"CoffeeWithJesus", "cogsci", "ColbertRally", "collapse", "college",
			"Colorado", "Columbus", "comedy", "comicbooks", "comics",
			"compsci", "computergraphics", "computers", "ComputerSecurity",
			"computervision", "conan", "conservation", "Conservative",
			"conspiracies", "conspiracy", "conspiratard", "Cooking", "cool",
			"copyfight", "cordcutters", "Corruption", "corsets", "COsnow",
			"cosplay", "coversongs", "cowboys", "cpop", "cpp", "C_Programming",
			"CR48", "craigslist", "Crainn", "CrappyDesign", "CreationKit",
			"creepy", "creepygaming", "Creepygifs", "Cricket", "crime",
			"crossfit", "CrossView", "crustpunk", "crypto", "css", "csun",
			"cubeworldproblems", "culturalstudies", "culture", "CURRENTEVENTS",
			"cute", "CuteGayPics", "cyberlaws", "Cyberpunk_Music", "cycling",
			"czech", "d1g", "daddit", "DAE", "daily", "Dallas", "DanishEnts",
			"DarkSoulsHelp", "darkstep", "datasets", "Daww", "dcpu16",
			"dcuonline", "de", "deadpets", "DebateaCommunist",
			"DebateReligion", "DecidingToBeBetter", "Deepconnection",
			"DeepSpaceNine", "democrats", "demsocialist", "Denmark",
			"dependent_types", "depression", "DescentIntoTyranny", "Design",
			"designthought", "DesktopDetective", "Detroit", "DetroitRedWings",
			"deutschland", "diablo3", "digitaladvertising",
			"digitaljournalism", "disability", "discgolf", "Disgaea", "DIY",
			"django", "DJs", "dkpol", "DnB", "doctorwho", "Documentaries",
			"DocumentedTruth", "DoesAnybodyElse", "Dogfort", "DogFortPic",
			"dogs", "Dogtraining", "Dokumentationen", "doodleordie",
			"DosugPoRuskij", "dotnet", "dragonage", "drawsome", "Dreams",
			"droid", "Drugs", "drums", "drunk", "drupal", "dubstep", "Ducati",
			"dungeondefenders", "dustforce", "dwarffortress", "dykesgonemild",
			"EarthPorn", "EarthScience", "Ebay", "ebooks", "ECE", "Economics",
			"economics2", "economy", "EconPapers", "ECW", "EdBangerRecords",
			"editors", "Edmonton", "edmontonsocialclub", "edmproduction",
			"education", "education2", "EFLcomics", "egalitarian", "eHost",
			"ektenyheter", "eldertrees", "electionreform",
			"electronic_cigarette", "electronicdancemusic", "electronicmusic",
			"electronics", "emacs", "EmmaWatson", "Employment", "energy",
			"engineering", "england", "entertainment", "enthouse",
			"Entomology", "Entrepreneur", "Entroductions", "entwives",
			"environment", "environment2", "episodehub", "Equality",
			"EQUIPnTRIP", "Eredivisie", "erlang", "es", "esports",
			"esportsvideos", "europe", "Eve", "evedreddit", "evolution",
			"evolutionReddit", "exmormon", "explainlikeimfive", "ExposurePorn",
			"eyes", "facebook", "facebookquotes", "Fahrvergnugen", "fail",
			"falsemetal", "Fantasy", "fantasyfb", "fantasyfootball",
			"FantasyMuscle", "farming", "fashion", "Favors", "FBcovers",
			"feminisms", "fffffffuuuuuuuuuuuu", "fffffffuuuuuuuuuuuud",
			"fiction", "FifthWorldPics", "fillthegaps", "FIlm", "FilmFaces",
			"filmphotos", "filteredgaming", "filth", "finance",
			"financialindependence", "FinancialPlanning", "FindAGame",
			"finddit", "FindTheOthers", "firefox", "firstamendment",
			"firstworldanarchists", "Fishing", "Fitment", "Fitness",
			"FixedAndSingleSpeed", "FixedGearBicycle", "Fixxit", "flash",
			"flickr", "florida", "FML", "food", "food2", "Foodforthought",
			"FoodPorn", "football", "footballtactics", "foreveraloneteens",
			"forhire", "formula1", "FortPorn", "fossworldproblems",
			"FragReddit", "france", "FREE", "freebies", "FreebiesUK",
			"freeculture", "freedomearth", "freegames", "freemusic",
			"FreePolitics", "Freethought", "friendship", "Frugal",
			"FrugalFemaleFashion", "FRUITUNION", "fsharp", "funny", "furry",
			"futurama", "futurepopmusic", "FWEPP", "gadgets", "GalaxyNexus",
			"gamecollecting", "GameDeals", "gamedev", "gamemechanics",
			"gamemusic", "GameRanks", "gamereviews", "gamernews", "gamerpics",
			"Games", "gameswap", "gamewallpaper", "gaming", "gamingnews",
			"gamingpc", "GamingPorn", "gamingsuggestions", "gardening",
			"gaybros", "gaymers", "GaymersGoneMild", "gearedup", "geek",
			"Geeked", "Genealogy", "general", "gentlemanimals", "Gentoo",
			"geography", "geology", "geospatial", "germany", "gggg",
			"GhettoJerk", "Ghosts", "gif", "gifs", "GifSound", "GirlGamers",
			"git", "Glitch_in_the_Matrix", "Glitchop", "globalhealth",
			"glutenfree", "gnu", "GNV", "golang", "golf", "google",
			"googleplus", "googleplusinvites", "government", "GradSchool",
			"Graffiti", "grammar", "GrandTheftAutoV", "graphic_design",
			"Graviga", "GreaseMonkey", "greatnewseveryone", "greed", "Green",
			"greencars", "greenery", "group_help_dating", "gtamarketplace",
			"GuessMyFirstName", "guildwars2funny", "Guitar",
			"guitarcirclejerk", "Gulf", "gundem", "Gunners", "guns",
			"Gymnastics", "hackers", "hackerspaces", "hacking", "haiku",
			"HailCorporate", "halifax", "halloween", "Hamilton", "Hammocks",
			"happentobegay", "happy", "HappyBirthday", "hardbodies",
			"HardcoreSMP", "hardshipmates", "hardtrance", "hardware",
			"harrypotheads", "HarryPotterGoneWild", "haskell", "HDGoPro",
			"HeadBangToThis", "Health", "health2", "Heavymind", "Helicopters",
			"help", "helpit", "HelpoutReddit", "hemp", "heythatwasin", "HIFW",
			"hiphop", "hip_hop", "Hiphopcirclejerk", "hiphopheads",
			"hiphoptruth", "HIPSTERGURLZ", "hipsters", "hispanicmusic",
			"history", "HITsWorthTurkingFor", "hockey", "homebrew",
			"Homebrewing", "homeland", "homeowners", "homestead", "horror",
			"Horses", "houston", "howto", "howtonotgiveafuck", "html5",
			"Humaneness", "humanrights", "humansinc", "humor", "Hunting",
			"HuntsvilleAlabama", "IAmA", "IAmAFiction", "ICanDrawThat",
			"Iceland", "ICoveredASong", "IDAP", "ideasfortheadmins", "idm",
			"idrew", "ifyoulikeblank", "IGQA", "IHateFoxNews",
			"iiiiiiitttttttttttt", "ILiveIn", "Image", "impoliteconversation",
			"independent", "indepthstories", "india", "IndieFolk",
			"IndieGaming", "indierock", "indie_rock", "Indoctrinated",
			"indonesia", "Industrialporn", "ineedafavor", "Infographics",
			"InfrastructurePorn", "Inglip", "InspectorSpacetime",
			"inspirational", "Intelligence", "investing", "Invites",
			"IOGraphicPorn", "iosgaming", "Iowa", "ipad", "iphone",
			"iPhoneDev", "iphoneWallpaper", "iran", "ireland", "IrishHistory",
			"islam", "Israel", "israelexposed", "it", "italy", "itookapicture",
			"ItsTheFuture", "iWallpaper", "IWantOut", "IWantToLearn", "ja",
			"jackrussellterrier", "JailbaitJunkies", "jambands", "japan",
			"japanese_teen_idols", "java", "javascript", "Jazz", "jazzhop",
			"jobs", "Jokes", "JoshHutcherson", "jquery", "Judaism",
			"JudgeMyArt", "justvent", "Juve", "kansascity", "karmacidewatch",
			"KarmaConspiracy", "katawashoujo", "kde", "KDRAMA", "kendo",
			"KerbalSpaceProgram", "knitting", "knives", "Koans", "KONY",
			"KONY2012", "korea", "kratom", "l4d2", "LadyBoners",
			"ladyladyboners", "LAGTV", "language", "LANL_Spanish", "latin",
			"LaughOrCry", "law", "LaymanJournals", "lds", "leafs",
			"leagueoflegends", "LeagueOfMemes", "Leakspin", "LearnJapanese",
			"learnmath", "Learnmusic", "learnprogramming", "lectures",
			"left4dead", "left4dead2", "lego", "LetsNotMeet", "LetsTalkMusic",
			"lfg", "lgbt", "Liberal", "Libertarian", "libertariancomics",
			"libertarian_history", "LibertarianLeft", "Libertario", "Liberty",
			"Libraries", "libredesign", "Life", "LifeProTips", "lifestyle",
			"linguistics", "linux", "linux4noobs", "LinuxActionShow",
			"linuxadmin", "linux_devices", "linux_gaming", "linuxquestions",
			"liquiddnb", "lisp", "listentomusic", "listentothis",
			"listofponies", "lists", "literature", "litvideos", "LiverpoolFC",
			"logic", "logiciels_libres", "lol", "lolcast", "lolcats",
			"LoLCodeTrade", "london", "longboarding", "lookatmydog",
			"lookoftheday", "LosAngeles", "loseit_classic", "lost",
			"lostgeneration", "Louisiana", "love", "Lovecraft", "lua",
			"lxnews", "mac", "macapps", "MachineLearning", "Magicdeckbuilding",
			"magicTCG", "Maine", "makecomics", "makinghiphop", "malaysia",
			"malefashionadvice", "malemodels", "management", "manchester",
			"MapPorn", "Marijuana", "MarketAnarchism", "marketing", "Mars",
			"mashups", "massage", "math", "mathbooks", "matheducation",
			"maturepolitics", "mcpubliccirclejerk", "mctourney", "meat",
			"MECoOp", "media", "medicalschool", "medicine", "meetup",
			"MelanieLaurent", "melbourne", "melodichardcore", "melodicmetal",
			"MemePiece", "memphis", "MensRights", "mensrightslinks", "Metal",
			"MetalCovers", "metamoderatorjerk", "mexico", "Miami", "Michigan",
			"microsoft", "MiddleEasternMusic", "MiddleEastNews", "Midwives",
			"mildlyinteresting", "mileycyrus", "Military", "Militaryraging",
			"mindcrack", "Minecraft", "MinecraftMadWorld", "minecraftmaps",
			"minecraftseeds", "MinecraftWars", "minerapocalypse", "minimal",
			"minimalism", "minnesota", "mises", "missA", "MissingPersons",
			"missouristate", "mixcd", "mixes", "MLPLounge", "mlpmature",
			"MLPvectors", "MMA", "mmafights", "MMFB", "MMJ", "mmo",
			"MobileGames", "modclub", "ModdingMC", "ModerationLog",
			"ModerationPorn", "Modern_Family", "modhelp",
			"ModsAreKillingReddit", "montreal", "MontrealEnts", "mormon",
			"morrissey", "motorcycles", "motorsports", "movieclub",
			"moviecritic", "MoviePosterPorn", "movies", "moviescirclejerk",
			"Movieswhilehigh", "mspaint", "MST3K", "mumbai", "museum", "Music",
			"musicians", "musicmakers", "MusicMods", "MusicNews", "musicpics",
			"MW2", "MW3Elite", "mycology", "mylittleandysonic1",
			"mylittledaww", "mylittlefanfic", "mylittlehuman",
			"mylittlenanners", "mylittleonions", "n900", "NAE3", "nanotech",
			"narwhals", "NativeAmerican", "naturalstate", "nature", "nba",
			"neckbeardrights", "needadvice", "neopagan", "nerdcorepodcast",
			"netflix", "netsec", "networking", "neuro", "Neuropsychology",
			"NewAgeMusic", "NewAgeReligion", "newbrunswickcanada", "newhaven",
			"newmusic", "newreddits", "new_right", "news", "newspapers",
			"NewToTF2", "newyork", "newzealand", "nextdoorasians",
			"nfffffffluuuuuuuuuuuu", "nfl", "nflcirclejerk", "NFLOffTopic",
			"nhl", "NigelThornberry", "Nobodylikesonions", "NoFap",
			"noisefuck", "NonAustrianEconomics", "nonprofit", "Nootropics",
			"norge", "NORML", "nosleep", "nostalgia", "notjackiechan",
			"NoveltyAccounts", "nyc", "nzsucks", "obama", "Objectivism",
			"ocaml", "Occupy", "occupyaustin", "OccupyBoston", "occupychi",
			"occupyDC", "occupylosangeles", "occupyOakland", "OccupyPhilly",
			"occupyseattle", "Oddball", "offbeat", "Ohio", "oilspill",
			"OkCupid", "oklahoma", "OldSchoolCool", "OldSkool_RaveAnthems",
			"omegle", "OneParagraph", "OnePiece", "OneY", "opendirectories",
			"openkinect", "opensource", "operabrowser", "OperationCorkscrew",
			"OperationGrabAss", "OperationPullRyan", "oregon",
			"OrthodoxChristianity", "otomata", "ottawa", "our", "Outdoors",
			"overpopulation", "ows", "p2p", "p2pfoundation", "pakistan",
			"paleonews", "Paranormal", "Parenting", "ParticlePhysics",
			"pathofexile", "patientgamers", "pcgaming", "peloton", "penpals",
			"peoplesparty", "Percussionists", "perl", "Permaculture",
			"personalfinance", "Pets", "philadelphia", "philosophy",
			"PhilosophyofScience", "phish", "photoaday", "photobomb",
			"photocritique", "PhotoEdited", "photography", "photos",
			"photoshop", "PHP", "Physics", "piano", "pic", "pickup", "pics",
			"PictureChallenge", "Pictures", "piercing", "pillowmen",
			"pimpmyreddit", "pinball", "Piracy", "piratenpartei",
			"PirateParty", "pirateradio", "pittsburgh", "PixelArt", "Pizza",
			"pkmntcgtrades", "plasmacosmology", "Playdate", "playitforward",
			"PoeticReddit", "Poetry", "PokeFake", "PokemonLeagueDS",
			"pokemonrp", "poker", "POL_IT", "PoliticalHumor",
			"PoliticalModeration", "politics", "politics2",
			"Politics_Uncensored", "Polska", "polyamory", "ponypapers",
			"popcult", "PornOverlords", "Portland", "postprocessing",
			"postrock", "Pottery", "PPC", "pranks", "preteen_bitches",
			"preteen_girls", "preteenpussy", "PrettyGirls", "PRICXwatch",
			"primeinstantvideos", "privacy", "privvit", "prochoice",
			"productivity", "professionalcycling", "ProGMO", "programming",
			"progressive", "progrockmusic", "Project420", "ProjectAwesome",
			"ProjectCairo", "ProjectEnrichment", "projectmanagement",
			"Proofreading", "proper", "ProsePorn", "PS3", "ps3cfw",
			"ps3homebrew", "Psybient", "psychedelicrock", "psychology",
			"Psychonaut", "psychopharmacology", "punk", "Punkskahardcore",
			"Putin2012", "puzzles", "Python", "Quakers", "Quebec", "quotes",
			"QuotesPorn", "racism", "RacistReddit", "radiohead", "radioreddit",
			"ragelationships", "ragenovels", "RageOps", "rails", "raisingkids",
			"rally", "randomactsofbicycle", "Random_Acts_of_Books",
			"RandomActsOfChristmas", "RandomActsOfCookies",
			"RandomDeclarations", "RandomKindness", "RandomMail", "rant",
			"rap", "RapidshareList", "RBI", "reactiongifs", "realasians",
			"RealEstate", "realitianity", "recipes", "recordedmusic",
			"Reddionic", "redditatwork", "redditbooks", "RedditDayOf",
			"redditdev", "REDDITEXCHANGE", "redditgetsdrawn", "redditguild",
			"reddithax", "Redditimprov", "RedditMCWorld", "redditmusicclub",
			"redditoroftheday", "redditstories", "RedditThroughHistory",
			"reddittotp", "Redskins", "redsox", "reggae",
			"relationship_advice", "Relax", "religion", "ReligionInAmerica",
			"religiousright", "Repordy", "reportthespammers", "Reprap",
			"Republican", "RepublicOfAtheism", "RepublicOfFunny",
			"RepublicOfGaming", "RepublicOfModeration", "RepublicOfMusic",
			"RepublicOfNews", "RepublicOfPics", "RepublicOfPolitics",
			"RepublicOfReddit", "ReverseEngineering", "ReviewThis", "Ringer",
			"rit", "ro", "robotics", "RoCirclejerk", "Rockband", "rockbusters",
			"roguelikes", "RomeSweetRome", "ronpaul", "Roseville", "rpa",
			"rpg", "rpg_gamers", "RPGhumor", "RPI", "ruby", "rugbyunion",
			"RUGC", "RumourMill", "runescape", "running", "russia", "russian",
			"Russianlessons", "rwb", "sabres", "saddestof", "saiga", "sailing",
			"SampleSize", "sandiego", "sanfrancisco", "SanJoseSharks",
			"santacruzlocals", "scala", "ScamWatch", "ScaryStoriesSeries",
			"scheme", "science", "science2", "scientology", "scifi",
			"SciFiScroll", "Scotch", "Scotland", "Screenwriting",
			"Scriptcraftguild", "ScriptSwap", "Seattle", "SEC", "secondlife",
			"secretgentlemansclub", "secretpalace", "secretsanta", "seduction",
			"self", "selfhelp", "SelfSufficiency", "semanticweb", "SEO", "sex",
			"Sexy", "SexyAthletes", "sexymusic", "SexyWallpapers", "SF4",
			"SFstories", "shadowside", "shamelessplug", "shareastory",
			"sharedota2", "ShitBrix", "Shitsnoopdoes", "shittyadvice",
			"shittyadviceanimals", "shittyama", "shittyaskhistory",
			"shittyaskscience", "ShittyPoetry", "shittyreactiongifs",
			"ShittyTheoryOfReddit", "Shortfilms", "shutupandtakemymoney",
			"Silverbugs", "simpleios", "simpleliving", "sinema", "singapore",
			"singularity", "skateboarding", "skeptic", "SketchComedy",
			"skiing", "skulls", "skylanders", "skyrim", "SkyrimHelp",
			"SkyrimPorn", "slackerrecipes", "slashdiablo", "sleepy",
			"Sliphorn", "smallbusiness", "snackexchange", "SNCA",
			"snowboarding", "soapier", "soccer", "socialism", "Socialist",
			"socialmedia", "socialscience", "socialskills", "sociology",
			"sodypop", "software", "SomebodyMakeThis", "somethingimade",
			"SomethingNew", "SOPAfunny", "SOS", "SoulCaliburV",
			"SoundsVintage", "southafrica", "SouthAfrican", "southcarolina",
			"space", "Spacefleet", "spaceflight", "spaceribs", "SpideyMeme",
			"Spiritpokemon", "sport", "sports", "SportsBlogs", "sportsvideo",
			"spotify", "SquaredCircle", "srsbonersforeverybody", "SRSBusiness",
			"SRSDiscussion", "SRSGSM", "SRSHappy", "SRSMeta", "SRSMusic",
			"SRSNews", "SRSPonies", "SRSPUA", "StandUpComedy",
			"StanleyKubrick", "starbound", "starcraft", "starcraft2",
			"StarcraftFeedback", "stare_dad", "starlets", "startrek",
			"startups", "StarWars", "statistics", "steamcoupons", "SteamGifts",
			"steampunk", "steamtrades", "stencils", "StLouis", "sto", "stocks",
			"StonerEngineering", "stonerrock", "StopBullyingComics",
			"stopsmoking", "strictlyworldpolitics", "studentchallenge",
			"SuicideWatch", "summercamphunt", "summonerschool", "Sunlight",
			"Suomi", "surfing", "surfporn", "Survivalist", "survivorzero",
			"sustainability", "SwingMusic", "switcharoo", "Switzerland",
			"SWOldRepublic", "sydney", "synthesizers", "sysadmin", "sysor",
			"t:1558", "t:1780", "t:1800s", "t:1910s", "t:1920s", "t:1930s",
			"t:1942", "t:1955", "t:1980s", "t:1984", "t:1985", "t:1990s",
			"t:2000s", "t:2011", "t:2013", "t:2021", "t:2022", "t:2050",
			"t:2112", "t:2525", "t:2999", "t:3000", "t:400bc", "t:42000",
			"t:800bc", "t:9000", "tabled", "Tacoma", "tamil", "taoism",
			"TAtalk", "tattoos", "tax", "t:bigbang", "t:cretaceous", "tea",
			"TeamRedditTeams", "tea_party", "technews", "TechNewsToday",
			"TechnicalDeathMetal", "technology", "technology2",
			"TechnologyBlogs", "techsupport", "techtheatre", "ted", "tedtalks",
			"teen_girls", "TeenGirls", "teenmodels", "Tekken", "television",
			"tentporn", "TenYearsAgo", "terriblefacebookmemes", "teslore",
			"test", "texas", "TextSalad", "tf2", "TF2fashionadvice", "TF2LFT",
			"tf2replays", "Tf2Scripts", "tf2trade", "TF2Unusuals",
			"t:heatdeathoftheuniverse", "Theatre", "thegreatproject",
			"TheMakingOf", "ThePromisedLand", "TheWire", "threads", "threejs",
			"thronescomics", "tifu", "timelapse", "timereddits",
			"timetolegalize", "tinycode", "tipofmytongue", "t:latestoneage",
			"tldr", "tldrfilms", "TodayIDrew", "todayilearned",
			"togetheralone", "toledo", "tolkienfans", "tonightsdinner",
			"ToolBand", "TopGear", "topwalls", "toronto", "torrents",
			"TotallyTennessee", "ToTheRescue", "trackers", "tradingfaces",
			"trailerparkboys", "trance", "transgender", "Transhuman",
			"transit", "translator", "transpositive", "TransSpace",
			"trapmuzik", "travel", "treecomics", "TreeConnoisseurs",
			"treedibles", "treejams", "treemusic", "trees", "treesdating",
			"Treewriting", "t:renaissance", "triangle", "tribalhero", "trippy",
			"trollcave", "t:romanempire", "troubledteens", "TrueBlood",
			"TrueFilm", "trueMusic", "TrueReddit", "truetf2", "TruthDare",
			"TruthInPolitics", "t:tomorrow", "tvcritic", "t:victorian",
			"TvTrailers", "TwilightWithBooks", "TwinCities",
			"twincitiessocial", "TWiTGameOn", "Twitter", "TwoXChromosomes",
			"t:yesterday", "typography", "t:zero", "Ubuntu", "udk", "UFO_2012",
			"UFOs", "UIUC", "ukhiphopheads", "ukpolitics", "uktrees",
			"ultimate", "under10k", "UnderratedGames", "unitedkingdom",
			"Unity3D", "unity_games", "UniversityofReddit", "unixporn", "unr",
			"UnsentMusic", "urbanplanning", "USNEWS", "UUreddit",
			"vaguequestions", "vancouver", "veg", "vegan", "vegas",
			"Vegetarianism", "venturebros", "vertical", "VictoriaBC", "video",
			"videos", "VillagePorn", "vinyl", "vinylscratch", "Virginia",
			"visualization", "vmware", "vodka", "voluntarism", "VolvoRWD",
			"vorg", "VXJunkies", "wadsworth", "Wake", "Wales", "wallpaper",
			"wallpapers", "wargames", "WarshipPorn", "washingtondc", "water",
			"waterporn", "waveinvites", "WeAreTheFilmMakers",
			"WeAreTheMusicMakers", "weather", "webcomics", "web_design",
			"webdev", "Web_Development", "WebGames", "webhosting", "webos",
			"wedding", "weeaboo", "weed", "weightroom", "wemetonline",
			"wenyude", "WesterosiProblems", "westtoo", "whalebait",
			"whatIthinkIdo", "Whatsinmycupboard", "whatsthisworth", "whedon",
			"WhiteMenGoneWild", "WhiteNationalism", "whyineedtoberich",
			"WhyWeSmoke", "wii", "wikipedia", "Wildlife", "windows",
			"windowshots", "wine", "winemaking", "wisconsin", "witcher",
			"woahdude", "wolfattacks", "women", "womenrock", "wordcount",
			"Wordpress", "work", "worldbuilding", "worldevents", "worldnews",
			"worldpolitics", "worstof", "WouldYouRather", "wow", "wowscrolls",
			"woXChromosomes", "wp7dev", "WrestlingVideos", "WritersGroup",
			"writing", "WTF", "WTF_Florida", "wtfstockphotos", "WWE", "xbmc",
			"xbox360", "xkcd", "xss", "yahooanswers", "yalesom2013", "yankees",
			"yishansucks", "youngatheists", "YouShouldKnow", "youtube",
			"youtubehaiku", "zen", "ZenHabits", "zombies", "Zune" };

}
